### ISSUE TITLE
Hey - added some node endpoint requests

### ISSUE THREAD

**Issue by DrunkenMoose** [alien-valley/znn.js#1]
Hey Alien Valley,

I saw your JS SDK and thought it was a good entry point into learning about the Zenon Network and how this is all structured.
Currently I have finished the znnplayground found here: [https://znnplayground.com/](url). (It only works on http now for a WS/HTTP request, otherwise you get a SSL error)

I added more function to the src folder, do you want that file (I just copied all the requests basically, not written custom ones). But I managed to make the websocket and http request use the same structure you provided. Now I will continue to learn about the network and see if I can build some more onto it.

**Comment by av-vonsbak** [comment]
Hello

Let's try to move this conversation over on [telegram](https://t.me/vonsbak). I'll love to talk more about this <3

I'll love to include the endpoints provided by you in the repo. Let me know where I can find the codebase.

My thoughts are to integrate all the changes under `src/` in _znn.js_ and have znnplayground use the library (as a webpack most probably). I'll love to have the znnplayground as an example on how to use the SDK since it should cover all functionality.

Let me know what you think.

**Comment by av-vonsbak** [comment]
Merged in b81377281a645df74fc660b68a0a2e196a5003e0
Thanks!
